version: "3.1"

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181

  kafka1:
    image: codingfanlt/kafka
    restart: always
    hostname: localhost
    ports:
      - 9092:9092
    environment:
      BROKER_ID: 0
      ZOO_SERVERS: zoo1:2181
